:important-caption: :heavy_exclamation_mark:

link:../README.adoc[← Table of Contents]

== Regeln für die Erinnerungsfunktion

=== 7 Tage Modus (nicht Short-track)

==== A - Initialer Download

Trigger: User logt sich das erste mal in der App ein Aktion: Versende
Erinnerungstext morgens um 6 Uhr ``Es liegt ein neuer Fragebogen für
Sie bereit'' Ende: Participant lädt Fragebogen runter oder vier Erinnerungen
wurden versendet / vier Tage sind vergangen

DB-Zustand: Start_Date und Due_Date in Participant gesetzt && Due Date nicht
überschritten && *kein* Eintrag in History Table

==== B - Beantworten des Fragebogens

Trigger: Participant lädt Fragebogen runter Aktion: Versende Erinnerungstext
morgens um 6 Uhr ``Bitte denken Sie an das Absenden Ihres
Fragebogens'' Ende: Participant lädt Fragebogen hoch oder vier Erinnerungen
wurden versendet / vier Tage sind vergangen

DB-Zustand: Start_Date und Due_Date in Participant gesetzt && Due Date nicht
überschritten && Eintrag in History Table mit `date_sent = null`

=== 2 Tage Modus (Short-track)

Trigger für den Modus: Meldebutton gedrückt oder ein Fragebogen mit
positiven Triggerfrage wurde abgesendet

==== C - Meldebutton

Trigger: Meldebutton gedrückt Aktion: Versende Erinnerungstext morgens
um 6 Uhr ``Bitte denken Sie an das Absenden Ihres Fragebogens''
(Etwas andere Wortwahl!!) Ende: Participant lädt Fragebogen hoch oder zwei 
Erinnerungen wurden versendet

DB-Zustand: Start_Date und Due_Date in Participant gesetzt && Due Date nicht
überschritten && Eintrag in History Table mit `date_sent = null` (wie
link:#b---beantworten-des-fragebogens[B], aber Achtung, da mehrere
Einträge in History Table vorhanden)

==== D - Triggerfrage - Noch nicht geladen

Trigger: Fragebogen mit positiven Triggerfragen wurde abgesendet Aktion:
Versende Erinnerungstext morgens um 6 Uhr ``Es liegt ein neuer
Fragebogen für Sie bereit'' Versende Erinnerungstext sofort ``Es
liegt ein neuer Fragebogen für Sie bereit'' (kann das die App nicht
machen?) Ende: Participant lädt Fragebogen runter oder zwei Erinnerungen wurden
versendet

DB-Zustand: Start_Date und Due_Date in Participant gesetzt && Due Date nicht
überschritten && *kein* Eintrag in History Table (wie
link:#a---initialer-download[A])

==== E - Triggerfrage - Geladen

Trigger: Fragebogen mit positiven Triggerfragen wurde abgesendet Aktion:
Versende Erinnerungstext morgens um 6 Uhr ``Bitte denken Sie an das
Absenden Ihres Fragebogens'' Ende: Participant lädt Fragebogen hoch oder
zwei Erinnerungen wurden versendet

DB-Zustand: Start_Date und Due_Date in Participant gesetzt && Due Date nicht
überschritten && Eintrag in History Table mit `date_sent = null` (wie
link:#b---beantworten-des-fragebogens[B])
