# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: main workflow
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    run_tests:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 24
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: cache node_modules
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: ${{ runner.OS }}-build-${{ env.cache-name }}-
                      ${{ runner.OS }}-build-
                      ${{ runner.OS }}-
            - name: install npm
              run: npm install -g npm@latest
            - name: install node dependencies
              run: npm ci
              env:
                  CI: true
            - name: create /private key pair
              run: openssl genpkey -algorithm RSA -out private_key.pem -pkeyopt rsa_keygen_bits:4096
            - name: create public key
              run: openssl rsa -pubout -in private_key.pem -out public_key.pem
            - name: run all tests
              run: npm test
    lint_annotations:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 24
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: cache node_modules
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: ${{ runner.OS }}-build-${{ env.cache-name }}-
                      ${{ runner.OS }}-build-
                      ${{ runner.OS }}-
            - name: install npm
              run: npm install -g npm@latest
            - name: install node dependencies
              run: npm ci
            - name: run lint and generate annotations
              run: npm run lint:annotate
